### ISSUE TITLE
Only one motor recognized

### ISSUE THREAD

**Issue by FloMarg** [cdbaird/TL-rotation-control#1]
I'm using rotation mount (ELL14) not rotation stage (ELL18) but it seems to be the same device for electronic part. Any idea on why your main.py program found 1 motor ("Tapedrive needs 2 motors, 1 found" error message)?

**Comment by FloMarg** [comment]
Big misunderstanding on my part, it was what i thought at the beginning, your program use 2 devices! Now it works, nice software, thank you.

**Comment by SinStalker** [comment]
How did you get it to recognize the two motors? I'm using the ELL18K and running the program gives me the same message above, "Tapedrive needs 2 motors, 1 found."
